# Generated by Buildr 1.4.10, change to your liking

# Version number for this release
VERSION_NUMBER = "1.2.9"
# Group identifier for your projects
GROUP = "geoip-api-java"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

define "geoip-api-java" do

  project.version = VERSION_NUMBER
  project.group = GROUP

  package(:jar)
end
